/* FILENAME: UNITS.H
 * PROGRAMMER: EF2
 * PURPOSE: Globe project declaration module.
 * LAST UPDATE: 13.06.2014
 */

#ifndef __UNITS_H_
#define __UNITS_H_

#include "anim.h"

/* Create information unit of animation function */
ef2UNIT * EF2_InfoUnitCreate( VOID );

/* Create geometric unit of animation function */
ef2UNIT * EF2_GobjUnitCreate( VOID );

#endif /* __UNITS_H_ */

/* END OF 'UNITS.H' FILE */
